import logging
from typing import Optional
import httpx

from app.config.settings import settings

logger = logging.getLogger("newsletter.utils.slack")


def send_slack_notification(
    title: str,
    tldr: str,
    issue_date: str,
    newsletter_url: Optional[str] = None
) -> bool:
    """Sends a newsletter notification to Slack via incoming webhook."""
    
    # 1. Validate Slack webhook URL
    if not settings.SLACK_WEBHOOK_URL:
        logger.info("Slack webhook URL is not configured in .env. Skipping Slack notification.")
        return False

    # 2. Build Slack message payload using Block Kit
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "📰 AI Weekly Newsletter Published",
                "emoji": True
            }
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Title:*\n{title}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Issue Date:*\n{issue_date}"
                }
            ]
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Executive Summary:*\n{tldr[:500]}{'...' if len(tldr) > 500 else ''}"
            }
        },
        {
            "type": "divider"
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "Generated by AI Weekly Newsletter Engine 🤖"
                }
            ]
        }
    ]

    # Add button if URL provided
    if newsletter_url:
        blocks.insert(-1, {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "View Full Newsletter",
                        "emoji": True
                    },
                    "url": newsletter_url,
                    "style": "primary"
                }
            ]
        })

    payload = {
        "text": f"AI Weekly Newsletter: {title}",
        "blocks": blocks
    }

    # 3. Send to Slack webhook
    try:
        logger.info("Sending newsletter notification to Slack...")
        
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                settings.SLACK_WEBHOOK_URL,
                json=payload,
                headers={"Content-Type": "application/json"}
            )
            
            if response.status_code == 200:
                logger.info("Slack notification sent successfully.")
                return True
            else:
                logger.error(f"Slack webhook returned status {response.status_code}: {response.text}")
                return False
                
    except httpx.TimeoutException:
        logger.error("Slack webhook request timed out.")
        return False
    except Exception as e:
        logger.error(f"Failed to send Slack notification: {e}")
        return False


def send_slack_error_alert(error_message: str, context: str = "Newsletter Generation") -> bool:
    """Sends an error alert to Slack for monitoring purposes."""
    
    if not settings.SLACK_WEBHOOK_URL:
        return False

    payload = {
        "text": f"⚠️ Error in {context}",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"⚠️ Error: {context}",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"```{error_message[:1500]}```"
                }
            }
        ]
    }

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                settings.SLACK_WEBHOOK_URL,
                json=payload,
                headers={"Content-Type": "application/json"}
            )
            return response.status_code == 200
    except Exception as e:
        logger.error(f"Failed to send Slack error alert: {e}")
        return False
